pipeline {
    agent none
    stages {
        stage ('carrental container creation') {
            agent { label 'docker' }
            steps {
                bash script.sh
            }

         }

       }
    }
