pipeline {
    agent none   // no global agent, stages will define their own
    stages {
        stage('carrental container creation') {
            agent { label 'docker' }   // run on agent with 'docker' label
            steps {
                sh 'bash script.sh'    // execute your script
            }
        }
    }
}
